[package]
name = "html_visualizer"
edition = "2021"
version = "0.2.0"
authors = ["Ringo Leese <webmaster@ringoleese.de>"]
readme = "README.md"
license = "CC0-1.0"

[dependencies]
color_processing = { path = "../lib" }
